import 'package:flutter/material.dart';

import '../../core/utils/upload_file_name.dart';
export '../../core/utils/upload_file_name.dart';

import '../../data/models/task_attachment.dart';

enum AttachmentPreviewKind { image, pdf, text, audio, unsupported }

bool isImageMime(String? mimeType, String fileName) {
  if (mimeType?.toLowerCase().startsWith('image/') == true) return true;
  return _imageExtensions.contains(_fileExt(fileName));
}

bool isImageAttachment(TaskAttachment attachment) {
  if (isImageMime(attachment.mimeType, attachment.fileName)) return true;
  final ext = attachment.fileExtension?.trim().toLowerCase();
  if (ext != null && _imageExtensions.contains(ext)) return true;
  final stored = attachment.storedFileName;
  if (stored != null && isImageMime(attachment.mimeType, stored)) return true;
  return false;
}

bool isPdfAttachment(TaskAttachment attachment) {
  return isPdfMime(attachment.mimeType, attachment.fileName);
}

bool isTextAttachment(TaskAttachment attachment) {
  return isTextPreviewMime(attachment.mimeType, attachment.fileName);
}

AttachmentPreviewKind previewKindFor(TaskAttachment attachment) {
  if (isImageAttachment(attachment)) {
    return AttachmentPreviewKind.image;
  }
  if (isPdfMime(attachment.mimeType, attachment.fileName)) {
    return AttachmentPreviewKind.pdf;
  }
  if (isTextPreviewMime(attachment.mimeType, attachment.fileName)) {
    return AttachmentPreviewKind.text;
  }
  if (isAudioMime(attachment.mimeType, attachment.fileName)) {
    return AttachmentPreviewKind.audio;
  }
  return AttachmentPreviewKind.unsupported;
}

bool isAudioAttachment(TaskAttachment attachment) {
  return isAudioMime(attachment.mimeType, attachment.fileName);
}

bool isAudioMime(String? mimeType, String fileName) {
  if (mimeType?.toLowerCase().startsWith('audio/') == true) return true;
  return _audioExtensions.contains(_fileExt(fileName));
}

String resolveAttachmentMimeType(TaskAttachment attachment) {
  final fromStored = attachment.storedFileName;
  if ((attachment.mimeType == null ||
          attachment.mimeType!.trim().isEmpty ||
          attachment.mimeType == 'application/octet-stream') &&
      fromStored != null) {
    return inferMimeTypeFromFileName(attachment.mimeType, fromStored);
  }
  return inferMimeTypeFromFileName(attachment.mimeType, attachment.fileName);
}

bool isPdfMime(String? mimeType, String fileName) {
  if (mimeType?.toLowerCase() == 'application/pdf') return true;
  return _fileExt(fileName) == 'pdf';
}

bool isTextPreviewMime(String? mimeType, String fileName) {
  final ext = _fileExt(fileName);
  if (ext == 'csv' || ext == 'json' || ext == 'txt' || ext == 'md') return true;
  final mime = mimeType?.toLowerCase() ?? '';
  return mime.startsWith('text/') ||
      mime == 'application/json' ||
      mime == 'text/csv';
}

bool isSvgMime(String? mimeType, String fileName) {
  if (mimeType?.toLowerCase() == 'image/svg+xml') return true;
  return _fileExt(fileName) == 'svg';
}

String inferMimeTypeFromFileName(String? mimeType, String fileName) {
  final normalized = mimeType?.trim().toLowerCase() ?? '';
  if (normalized.isNotEmpty && normalized != 'application/octet-stream') {
    return normalized;
  }
  const map = {
    'png': 'image/png',
    'jpg': 'image/jpeg',
    'jpeg': 'image/jpeg',
    'gif': 'image/gif',
    'webp': 'image/webp',
    'bmp': 'image/bmp',
    'svg': 'image/svg+xml',
    'pdf': 'application/pdf',
    'txt': 'text/plain',
    'md': 'text/markdown',
    'csv': 'text/csv',
    'json': 'application/json',
    'm4a': 'audio/mp4',
    'mp3': 'audio/mpeg',
    'aac': 'audio/aac',
    'wav': 'audio/wav',
    'ogg': 'audio/ogg',
    'webm': 'audio/webm',
  };
  return map[_fileExt(fileName)] ?? 'application/octet-stream';
}

String formatFileSize(int bytes) {
  if (bytes < 1024) return '$bytes B';
  if (bytes < 1024 * 1024) return '${(bytes / 1024).toStringAsFixed(1)} KB';
  return '${(bytes / (1024 * 1024)).toStringAsFixed(1)} MB';
}

String formatAttachmentDisplayName(
  String fileName, {
  int? index,
  String? mimeType,
}) {
  final trimmed = fileName.trim();
  if (trimmed.isEmpty || isAutoGeneratedAttachmentName(trimmed)) {
    final mime = mimeType?.toLowerCase() ?? '';
    final label = mime.startsWith('video/')
        ? 'Video'
        : mime.startsWith('audio/') ||
                trimmed.toLowerCase().startsWith('voice-')
            ? 'Voice note'
            : 'Photo';
    if (index != null) return '$label $index';
    return label == 'Voice note' ? 'Voice note' : '$label attachment';
  }
  if (trimmed.toLowerCase().startsWith('scaled_')) {
    final ext = _fileExt(trimmed);
    final base = index == null ? 'Photo attachment' : 'Photo $index';
    return ext.isEmpty ? base : '$base.$ext';
  }
  return trimmed;
}

String displayNameForAttachment(
  TaskAttachment attachment, {
  int? index,
}) {
  return formatAttachmentDisplayName(
    attachment.fileName,
    index: index,
    mimeType: attachment.mimeType,
  );
}

IconData iconForAttachment(TaskAttachment attachment) {
  final kind = previewKindFor(attachment);
  return switch (kind) {
    AttachmentPreviewKind.image => Icons.image_outlined,
    AttachmentPreviewKind.pdf => Icons.picture_as_pdf_outlined,
    AttachmentPreviewKind.text => Icons.description_outlined,
    AttachmentPreviewKind.audio => Icons.mic_rounded,
    AttachmentPreviewKind.unsupported => Icons.insert_drive_file_rounded,
  };
}

const _imageExtensions = {
  'png',
  'jpg',
  'jpeg',
  'gif',
  'webp',
  'bmp',
  'svg',
  'heic',
  'heif',
};

const _audioExtensions = {
  'm4a',
  'mp3',
  'aac',
  'wav',
  'ogg',
  'webm',
};

String _fileExt(String fileName) {
  final parts = fileName.split('.');
  if (parts.length < 2) return '';
  return parts.last.toLowerCase();
}
