#!/usr/bin/env bash
# Writes ios/.xcode.env.local so Xcode build scripts can find Flutter, CocoaPods, etc.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$ROOT/env.sh"

LOCAL_ENV="$ROOT/ios/.xcode.env.local"
{
  echo "# Auto-generated by scripts/write-xcode-env-local.sh — do not commit."
  echo "export FLUTTER_ROOT=\"$FLUTTER_ROOT\""
  echo "export PATH=\"/opt/homebrew/bin:$FLUTTER_ROOT/bin:\$PATH\""
  if command -v pod >/dev/null 2>&1; then
    echo "export PATH=\"$(dirname "$(command -v pod)"):\$PATH\""
  fi
} > "$LOCAL_ENV"

echo "Wrote $LOCAL_ENV"
