import 'package:intl/intl.dart';

bool isAutoGeneratedAttachmentName(String fileName) {
  final trimmed = fileName.trim();
  if (trimmed.isEmpty) return true;
  final lower = trimmed.toLowerCase();
  if (lower.startsWith('scaled_')) return true;
  if (lower.contains('scaled_')) return true;
  if (RegExp(r'^image_picker[_-]', caseSensitive: false).hasMatch(lower)) return true;
  if (RegExp(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', caseSensitive: false)
      .hasMatch(lower)) {
    return true;
  }
  return false;
}

String buildDefaultUploadFileName({String? mimeType, DateTime? timestamp}) {
  final stamp = DateFormat('yyyy-MM-dd HH.mm.ss').format(timestamp ?? DateTime.now());
  final mime = mimeType?.toLowerCase() ?? '';
  if (mime.startsWith('video/')) return 'Video $stamp.mp4';
  if (mime == 'application/pdf') return 'Document $stamp.pdf';
  return 'Photo $stamp.jpg';
}

String sanitizeUploadFileName(String fileName, {String? mimeType}) {
  final trimmed = fileName.trim();
  if (trimmed.isNotEmpty && !isAutoGeneratedAttachmentName(trimmed)) {
    return trimmed;
  }
  return buildDefaultUploadFileName(mimeType: mimeType);
}
