function formatUploadTimestamp(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}.${pad(date.getMinutes())}.${pad(date.getSeconds())}`;
}

export function isAutoGeneratedAttachmentName(fileName: string): boolean {
  const trimmed = fileName.trim();
  if (!trimmed) return true;
  const lower = trimmed.toLowerCase();
  if (lower.startsWith('scaled_')) return true;
  if (lower.includes('scaled_')) return true;
  if (/^image_picker[_-]/i.test(lower)) return true;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i.test(lower)) {
    return true;
  }
  return false;
}

export function buildDefaultUploadFileName(
  mimeType?: string | null,
  at: Date = new Date(),
): string {
  const stamp = formatUploadTimestamp(at);
  const mime = (mimeType ?? '').toLowerCase();
  if (mime.startsWith('video/')) return `Video ${stamp}.mp4`;
  if (mime === 'application/pdf') return `Document ${stamp}.pdf`;
  return `Photo ${stamp}.jpg`;
}

/** Friendly name stored in DB and shown in clients (camera/gallery auto-names replaced). */
export function resolveAttachmentDisplayName(
  fileName: string | null | undefined,
  mimeType?: string | null,
): string {
  const trimmed = (fileName ?? '').trim();
  if (!trimmed || isAutoGeneratedAttachmentName(trimmed)) {
    return buildDefaultUploadFileName(mimeType);
  }
  return trimmed;
}
