import {
  FileArchive,
  FileSpreadsheet,
  FileText,
  FileType,
  File as FileIcon,
  Image as ImageIcon,
  Mic,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { isOfficeDocumentPreviewable } from "@/lib/attachment-document-preview";

export function formatFileSize(bytes: number): string {
  if (!bytes || bytes <= 0) return "—";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function fileExt(fileName?: string): string {
  return fileName?.split(".").pop()?.toLowerCase() ?? "";
}

/** Normalize blob type so browsers can preview PDFs/images from generic octet-stream responses. */
export function ensurePreviewBlob(
  blob: Blob,
  mimeType?: string,
  fileName?: string
): Blob {
  if (isPdfMime(mimeType, fileName)) {
    return blob.type === "application/pdf"
      ? blob
      : new Blob([blob], { type: "application/pdf" });
  }
  if (isImageMime(mimeType, fileName)) {
    const target =
      mimeType?.startsWith("image/") ? mimeType : inferMimeTypeFromFileName(fileName);
    return blob.type.startsWith("image/") ? blob : new Blob([blob], { type: target });
  }
  if (isAudioMime(mimeType, fileName)) {
    const target =
      mimeType?.startsWith("audio/")
        ? mimeType.split(";")[0]!.trim()
        : inferMimeTypeFromFileName(fileName);
    return blob.type.startsWith("audio/") ? blob : new Blob([blob], { type: target });
  }
  return blob;
}

/** Best-effort MIME from filename when the API omits mimeType. */
export function inferMimeTypeFromFileName(fileName?: string): string {
  const ext = fileExt(fileName);
  const map: Record<string, string> = {
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    gif: "image/gif",
    webp: "image/webp",
    bmp: "image/bmp",
    svg: "image/svg+xml",
    pdf: "application/pdf",
    txt: "text/plain",
    csv: "text/csv",
    json: "application/json",
    zip: "application/zip",
    doc: "application/msword",
    docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    xls: "application/vnd.ms-excel",
    xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    xlsm: "application/vnd.ms-excel.sheet.macroenabled.12",
    ods: "application/vnd.oasis.opendocument.spreadsheet",
    m4a: "audio/mp4",
    mp3: "audio/mpeg",
    aac: "audio/aac",
    wav: "audio/wav",
    ogg: "audio/ogg",
    webm: "audio/webm",
  };
  return map[ext] ?? "application/octet-stream";
}

export function isImageMime(mimeType?: string, fileName?: string): boolean {
  if (mimeType?.startsWith("image/")) return true;
  const ext = fileExt(fileName);
  return ["png", "jpg", "jpeg", "gif", "webp", "bmp", "svg"].includes(ext);
}

export function isPdfMime(mimeType?: string, fileName?: string): boolean {
  if (mimeType === "application/pdf") return true;
  return fileExt(fileName) === "pdf";
}

export function isAudioMime(mimeType?: string, fileName?: string): boolean {
  if (mimeType?.toLowerCase().startsWith("audio/")) return true;
  // Chrome may label opus voice notes as video/webm
  if (
    mimeType?.toLowerCase() === "video/webm" &&
    fileName?.toLowerCase().startsWith("voice")
  ) {
    return true;
  }
  const ext = fileExt(fileName);
  return ["m4a", "mp3", "aac", "wav", "ogg", "webm"].includes(ext);
}

export function isLocallyPreviewableFile(file: File): boolean {
  return (
    isImageMime(file.type, file.name) ||
    isPdfMime(file.type, file.name) ||
    isTextPreviewMime(file.type, file.name) ||
    isAudioMime(file.type, file.name) ||
    isOfficeDocumentPreviewable(file.type, file.name)
  );
}

export function createLocalPreviewUrl(file: File): string {
  return URL.createObjectURL(file);
}

export function isTextPreviewMime(mimeType?: string, fileName?: string): boolean {
  const ext = fileExt(fileName);
  if (ext === "csv" || ext === "json" || ext === "txt") return true;
  return (
    Boolean(mimeType?.startsWith("text/")) ||
    mimeType === "application/json" ||
    mimeType === "text/csv"
  );
}

export function isAutoGeneratedAttachmentName(fileName: string): boolean {
  const trimmed = fileName.trim();
  if (!trimmed) return true;
  const lower = trimmed.toLowerCase();
  if (lower.startsWith("scaled_")) return true;
  if (lower.includes("scaled_")) return true;
  if (/^image_picker[_-]/i.test(lower)) return true;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i.test(lower)) {
    return true;
  }
  return false;
}

export function formatAttachmentDisplayName(
  fileName: string,
  options?: { index?: number; mimeType?: string }
): string {
  const trimmed = fileName.trim();
  if (!trimmed || isAutoGeneratedAttachmentName(trimmed)) {
    const mime = options?.mimeType?.toLowerCase() ?? "";
    const label = mime.startsWith("video/")
      ? "Video"
      : mime.startsWith("audio/") || trimmed.toLowerCase().startsWith("voice")
        ? "Voice note"
        : "Photo";
    if (options?.index != null) return `${label} ${options.index}`;
    return label === "Voice note" ? "Voice note" : `${label} attachment`;
  }
  if (trimmed.toLowerCase().startsWith("voice")) {
    return "Voice note";
  }
  return trimmed;
}

export function friendlyAttachmentLoadError(message: string): string {
  const lower = message.toLowerCase();
  if (
    lower.includes("404") ||
    lower.includes("not found") ||
    lower.includes("missing on the server") ||
    lower.includes("file missing")
  ) {
    return "This file was uploaded from mobile but is not on the server disk. Re-upload the photo from the app.";
  }
  return message;
}

export function getAttachmentFileIcon(
  mimeType?: string,
  fileName?: string
): { Icon: LucideIcon; label: string } {
  const ext = fileExt(fileName);
  if (isAudioMime(mimeType, fileName)) return { Icon: Mic, label: "Voice note" };
  if (isImageMime(mimeType, fileName)) return { Icon: ImageIcon, label: "Image" };
  if (isPdfMime(mimeType, fileName)) return { Icon: FileText, label: "PDF" };
  if (
    mimeType?.includes("spreadsheet") ||
    mimeType?.includes("excel") ||
    ext === "xls" ||
    ext === "xlsx" ||
    ext === "xlsm" ||
    ext === "ods" ||
    ext === "csv"
  ) {
    return { Icon: FileSpreadsheet, label: "Spreadsheet" };
  }
  if (mimeType?.includes("word") || ext === "doc" || ext === "docx") {
    return { Icon: FileType, label: "Document" };
  }
  if (mimeType?.includes("zip") || ext === "zip") {
    return { Icon: FileArchive, label: "Archive" };
  }
  return { Icon: FileIcon, label: "File" };
}
