export type Country = {
  iso: string;
  name: string;
  dialCode: string;
};

export const COUNTRIES: Country[] = [
  { iso: "US", name: "United States", dialCode: "1" },
  { iso: "GB", name: "United Kingdom", dialCode: "44" },
  { iso: "CA", name: "Canada", dialCode: "1" },
  { iso: "AU", name: "Australia", dialCode: "61" },
  { iso: "IN", name: "India", dialCode: "91" },
  { iso: "DE", name: "Germany", dialCode: "49" },
  { iso: "FR", name: "France", dialCode: "33" },
  { iso: "IT", name: "Italy", dialCode: "39" },
  { iso: "ES", name: "Spain", dialCode: "34" },
  { iso: "NL", name: "Netherlands", dialCode: "31" },
  { iso: "BE", name: "Belgium", dialCode: "32" },
  { iso: "CH", name: "Switzerland", dialCode: "41" },
  { iso: "AT", name: "Austria", dialCode: "43" },
  { iso: "SE", name: "Sweden", dialCode: "46" },
  { iso: "NO", name: "Norway", dialCode: "47" },
  { iso: "DK", name: "Denmark", dialCode: "45" },
  { iso: "FI", name: "Finland", dialCode: "358" },
  { iso: "IE", name: "Ireland", dialCode: "353" },
  { iso: "PT", name: "Portugal", dialCode: "351" },
  { iso: "PL", name: "Poland", dialCode: "48" },
  { iso: "CZ", name: "Czech Republic", dialCode: "420" },
  { iso: "RO", name: "Romania", dialCode: "40" },
  { iso: "HU", name: "Hungary", dialCode: "36" },
  { iso: "GR", name: "Greece", dialCode: "30" },
  { iso: "TR", name: "Turkey", dialCode: "90" },
  { iso: "RU", name: "Russia", dialCode: "7" },
  { iso: "UA", name: "Ukraine", dialCode: "380" },
  { iso: "IL", name: "Israel", dialCode: "972" },
  { iso: "AE", name: "United Arab Emirates", dialCode: "971" },
  { iso: "SA", name: "Saudi Arabia", dialCode: "966" },
  { iso: "EG", name: "Egypt", dialCode: "20" },
  { iso: "ZA", name: "South Africa", dialCode: "27" },
  { iso: "NG", name: "Nigeria", dialCode: "234" },
  { iso: "KE", name: "Kenya", dialCode: "254" },
  { iso: "GH", name: "Ghana", dialCode: "233" },
  { iso: "CN", name: "China", dialCode: "86" },
  { iso: "JP", name: "Japan", dialCode: "81" },
  { iso: "KR", name: "South Korea", dialCode: "82" },
  { iso: "TW", name: "Taiwan", dialCode: "886" },
  { iso: "HK", name: "Hong Kong", dialCode: "852" },
  { iso: "SG", name: "Singapore", dialCode: "65" },
  { iso: "MY", name: "Malaysia", dialCode: "60" },
  { iso: "TH", name: "Thailand", dialCode: "66" },
  { iso: "VN", name: "Vietnam", dialCode: "84" },
  { iso: "PH", name: "Philippines", dialCode: "63" },
  { iso: "ID", name: "Indonesia", dialCode: "62" },
  { iso: "PK", name: "Pakistan", dialCode: "92" },
  { iso: "BD", name: "Bangladesh", dialCode: "880" },
  { iso: "LK", name: "Sri Lanka", dialCode: "94" },
  { iso: "NP", name: "Nepal", dialCode: "977" },
  { iso: "NZ", name: "New Zealand", dialCode: "64" },
  { iso: "MX", name: "Mexico", dialCode: "52" },
  { iso: "BR", name: "Brazil", dialCode: "55" },
  { iso: "AR", name: "Argentina", dialCode: "54" },
  { iso: "CL", name: "Chile", dialCode: "56" },
  { iso: "CO", name: "Colombia", dialCode: "57" },
  { iso: "PE", name: "Peru", dialCode: "51" },
  { iso: "VE", name: "Venezuela", dialCode: "58" },
  { iso: "EC", name: "Ecuador", dialCode: "593" },
  { iso: "UY", name: "Uruguay", dialCode: "598" },
  { iso: "CR", name: "Costa Rica", dialCode: "506" },
  { iso: "PA", name: "Panama", dialCode: "507" },
  { iso: "DO", name: "Dominican Republic", dialCode: "1" },
  { iso: "PR", name: "Puerto Rico", dialCode: "1" },
  { iso: "JM", name: "Jamaica", dialCode: "1" },
  { iso: "IS", name: "Iceland", dialCode: "354" },
  { iso: "LU", name: "Luxembourg", dialCode: "352" },
  { iso: "SK", name: "Slovakia", dialCode: "421" },
  { iso: "SI", name: "Slovenia", dialCode: "386" },
  { iso: "HR", name: "Croatia", dialCode: "385" },
  { iso: "RS", name: "Serbia", dialCode: "381" },
  { iso: "BG", name: "Bulgaria", dialCode: "359" },
  { iso: "LT", name: "Lithuania", dialCode: "370" },
  { iso: "LV", name: "Latvia", dialCode: "371" },
  { iso: "EE", name: "Estonia", dialCode: "372" },
  { iso: "BY", name: "Belarus", dialCode: "375" },
  { iso: "KZ", name: "Kazakhstan", dialCode: "7" },
  { iso: "UZ", name: "Uzbekistan", dialCode: "998" },
  { iso: "QA", name: "Qatar", dialCode: "974" },
  { iso: "KW", name: "Kuwait", dialCode: "965" },
  { iso: "BH", name: "Bahrain", dialCode: "973" },
  { iso: "OM", name: "Oman", dialCode: "968" },
  { iso: "JO", name: "Jordan", dialCode: "962" },
  { iso: "LB", name: "Lebanon", dialCode: "961" },
  { iso: "IQ", name: "Iraq", dialCode: "964" },
  { iso: "IR", name: "Iran", dialCode: "98" },
  { iso: "MA", name: "Morocco", dialCode: "212" },
  { iso: "DZ", name: "Algeria", dialCode: "213" },
  { iso: "TN", name: "Tunisia", dialCode: "216" },
  { iso: "ET", name: "Ethiopia", dialCode: "251" },
  { iso: "TZ", name: "Tanzania", dialCode: "255" },
  { iso: "UG", name: "Uganda", dialCode: "256" },
  { iso: "ZW", name: "Zimbabwe", dialCode: "263" },
  { iso: "ZM", name: "Zambia", dialCode: "260" },
  { iso: "MM", name: "Myanmar", dialCode: "95" },
  { iso: "KH", name: "Cambodia", dialCode: "855" },
  { iso: "LA", name: "Laos", dialCode: "856" },
  { iso: "MN", name: "Mongolia", dialCode: "976" },
  { iso: "AF", name: "Afghanistan", dialCode: "93" },
];

export const DEFAULT_COUNTRY_ISO = "IN";

export function getCountryByIso(iso: string): Country | undefined {
  return COUNTRIES.find((c) => c.iso === iso);
}

export function formatFullPhone(countryIso: string, localNumber: string): string {
  const country = getCountryByIso(countryIso);
  const digits = localNumber.replace(/\D/g, "");
  if (!country || !digits) return "";
  return `+${country.dialCode}${digits}`;
}
